BlogBundle\Entity\Commentaire:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\CommentaireRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        contenu:
            type: string
            length: 255
        note:
            type: integer
    manyToOne:
        commentePar:
            targetEntity: User
            inversedBy: com
            cascade: [ persist ]
        articleAssocie:
            targetEntity: Article
            inversedBy: comArticle
            cascade: [ persist ]
    oneToMany:
        signalement:
            targetEntity: SignalementCom
            mappedBy: signale
